version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: cathedra-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cathedra_development
      POSTGRES_USER: cathedra_user
      POSTGRES_PASSWORD: cathedra_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
